src/models/alerts/views.py
from flask import Blueprint, render_template, request, session, redirect, url_for
from models.alerts.alert import Alert
from models.items.item import Item
import models.users.decorators as user_decorators

# store_blueprint = Blueprint('stores', __name__)
# print('why?')
alert_blueprint = Blueprint('alerts', __name__)


@alert_blueprint.route('/')
@user_decorators.requires_login
def index():
    pass
    # return "methods not method"

# so on a hunch i commented this out and now it works? what the actual fuck
# its methods, not method


@alert_blueprint.route('/new', methods=['GET', 'POST'])
# checks that the user is logged in
@user_decorators.requires_login
def create_alert():
    if request.method == 'POST':
        name = request.form['name']
        url = request.form['url']
        price_limit = float(request.form['price_limit'])

        # def __init__(self, name, url, price=None, _id=None):
        item = Item(name, url)
        item.save_to_mongo()

        alert = Alert(session['email'], price_limit, item._id)
        alert.load_item_price()  # Already saves to mongo

    return render_template('alerts/new_alert.html')


@alert_blueprint.route('/edit/<string:alert_id>', methods=['GET', 'POST'])
@user_decorators.requires_login
def edit_alert(alert_id):
    alert = Alert.find_by_id(alert_id)

    if request.method == 'POST':
        name = request.form['name']
        url = request.form['url']
        price_limit = request.form['price_limit']

        # so some of these are actually item properties
        alert.item.name = name
        alert.item.url = url
        alert.price_limit = price_limit

        # do i need to save the item?
        alert.save_to_mongo()
        # maybe?
        alert.item.save_to_mongo()

        return redirect(url_for('users.user_alerts'))

        # experimenting
        # return get_alert_page(alert_id)

    return render_template('alerts/edit_alert.html', alert=alert)


@alert_blueprint.route('/deactivate/<string:alert_id>')
@user_decorators.requires_login
def deactivate_alert(alert_id):
    Alert.find_by_id(alert_id).deactivate()
    return redirect(url_for('users.user_alerts'))


@alert_blueprint.route('/delete/<string:alert_id>')
@user_decorators.requires_login
def delete_alert(alert_id):
    Alert.find_by_id(alert_id).delete()
    return redirect(url_for('users.user_alerts'))


@alert_blueprint.route('/activate/<string:alert_id>')
@user_decorators.requires_login
def activate_alert(alert_id):
    Alert.find_by_id(alert_id).activate()
    return redirect(url_for('users.user_alerts'))


@alert_blueprint.route('/<string:alert_id>')
@user_decorators.requires_login
def get_alert_page(alert_id):
    # print('hello from get_alert_page the alert_id is: ', alert_id)
    alert = Alert.find_by_id(alert_id)
    return render_template('/alerts/alert.html', alert=alert)


@alert_blueprint.route('/check_price/<string:alert_id>')
def check_alert_price(alert_id):
    Alert.find_by_id(alert_id).load_item_price()
    return redirect(url_for('.get_alert_page', alert_id=alert_id))

src/models/stores/views.py
from flask import Blueprint, render_template, request, redirect, url_for
from models.stores.store import Store
import json

import models.users.decorators as user_decorators

store_blueprint = Blueprint('stores', __name__)


@store_blueprint.route('/')
def index():
    # print('should be getting here?')
    stores = Store.all()
    # return 'hello'
    return render_template('stores/store_index.html', stores=stores)


@store_blueprint.route('/store/<string:store_id>')
def store_page(store_id):
    return render_template('stores/store.html', store=Store.get_by_id(store_id))


@store_blueprint.route('/edit/<string:store_id>', methods=['GET', 'POST'])
@user_decorators.requires_admin_permission
def edit_store(store_id):
    store = Store.get_by_id(store_id)

    if request.method == 'POST':
        name = request.form['name']
        url_prefix = request.form['url_prefix']
        tag_name = request.form['tag_name']
        # beautiful soup expects a python dict, so you get the {"id": "price-now"}
        # as a json object, this converts is to a dict, it's actually already in that format anyway right? i think so
        query = json.loads(request.form['query'])

        # because you're working on an object that already exists
        # store = Store.get_by_id(store_id)

        store.name = name
        store.url_prefix = url_prefix
        store.tag_name = tag_name
        store.query = query

        store.save_to_mongo()

        return redirect(url_for('.index'))

    return render_template('stores/edit_store.html', store=store)


@store_blueprint.route('/delete/<string:store_id>', methods=['GET'])
@user_decorators.requires_admin_permission
def delete_store(store_id):
    Store.get_by_id(store_id).delete()
    return redirect(url_for('.index'))


@store_blueprint.route('/new', methods=['GET', 'POST'])
@user_decorators.requires_admin_permission
def create_store():
    if request.method == 'POST':
        # print('create_store here, am post data now?')
        name = request.form['name']
        url_prefix = request.form['url_prefix']
        tag_name = request.form['tag_name']
        # beautiful soup expects a python dict, so you get the {"id": "price-now"}
        # as a json object, this converts is to a dict, it's actually already in that format anyway right? i think so
        query = json.loads(request.form['query'])

        # signature of the store class
        # def __init__(self, name, url_prefix, tag_name, query, _id=None):
        Store(name, url_prefix, tag_name, query).save_to_mongo()

    return render_template('stores/new_store.html')

src/models/users/views.py
from flask import Blueprint, session, request, url_for, render_template
from werkzeug.utils import redirect

from models.users.user import User, UserError
import models.users.decorators as user_decorators

# print( type( user_decorators) )


user_blueprint = Blueprint('users', __name__)


@user_blueprint.route('/login', methods=['GET', 'POST'])
def login_user():
    if request.method == 'POST':
        # check login is valid
        email = request.form['email']
        password = request.form['password']

        try:
            if User.is_login_valid(email, password):
                session['email'] = email
                # gets the method user_alerts from the current location
                return redirect(url_for(".user_alerts"))
        except UserError.UserError as e:
            return e.message

    # send an error if the login was invalid
    return render_template("users/login.html")


@user_blueprint.route('/register', methods=['GET', 'POST'])
def register_user():
    if request.method == 'POST':
        # check login is valid
        email = request.form['email']
        password = request.form['password']

        try:
            if User.register_user(email, password):
                session['email'] = email
                # gets the method user_alerts from the current location
                return redirect(url_for(".user_alerts"))
        except UserError.UserError as e:
            # getting username does not exist here
            return e.message

    # changing this because i think it should be register
    # send an error if the login was invalid
    return render_template("users/register.html")


@user_blueprint.route('/alerts')
@user_decorators.requires_login
def user_alerts():
    user = User.find_by_email(session['email'])
    alerts = user.get_alerts()
    # the alert=alert passes the alert variable from above to the page so jinja can use it
    return render_template('users/alerts.html', alerts=alerts)


@user_blueprint.route('/logout')
def logout_user():
    session['email'] = None
    # home here is the base template in the app.py file which is why you don't need
    # any prefix information
    return redirect(url_for('home'))


@user_blueprint.route('/check_alerts/')
def check_user_alerts(user_id):
    pass

src/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Pricing service</title>

    <!--to include external libraries, like bootstrap-->
    <!--copies all the stuff from html_dependencies and includes it here, maintainability thing-->
    {% include "html_dependencies.html" %}


</head>

<body>

    <nav class="navbar navbar-default">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

                <a class="navbar-brand" href="/" title="home">Pricing</a>
            </div>

            <div id="navbar" class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="{{ url_for('stores.index') }}">Stores</a></li>
                    <!--<li><a href="{{ url_for('alerts.index') }}">Alerts</a></li>-->
                </ul>
                {% if session['email'] %}
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="{{ url_for('users.user_alerts') }}"><span class="glyphicon glyphicon-alert"></span>
                            Your alerts</a></li>
                    <li><a href="{{ url_for('users.logout_user') }}"><span class="glyphicon glyphicon-log-out"></span>
                            Log out</a></li>
                </ul>
                {% else %}
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="{{ url_for('users.register_user') }}"><span class="glyphicon glyphicon-user"></span>
                            Sign up</a></li>
                    <li><a href="{{ url_for('users.login_user') }}"><span class="glyphicon glyphicon-log-in"></span>
                            Login</a></li>
                </ul>
                {% endif %}
            </div>
        </div>
    </nav>

    <div class="content container">
        {% block content %}


        {% endblock %}
    </div>
</body>

</html>

src/templates/home.html
{% extends "base.html" %}

{% block content %}
<div class="jumbotron">
    <h1>Pricing service</h1>
    <p>We scan online store websites to alert you to price drops that interest you.</p>
    <p>Get started by adding the URL of an item you wish to track. We'll do the rest</p>
    <p><a class="btn btn-primary btn-lg" href="{{ url_for('users.register_user') }}" role="button">Sign up</a></p>
</div>
{% endblock %}

src/templates/html_dependencies.html
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
    crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp"
    crossorigin="anonymous">


<!--jQuery, remember that you have to load the script that others depend on first, otherwise it won't work-->
<script src="https://code.jquery.com/jquery-3.2.0.js" integrity="sha256-wPFJNIFlVY49B+CuAIrDr932XSb6Jk3J1M22M3E2ylQ="
    crossorigin="anonymous">

</script>


<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
    crossorigin="anonymous"></script>



<link rel="stylesheet" href="{{url_for('static', filename='css/style.css')}}">

src/templates/store_index.html
{% extends "base.html" %}

{% block content %}
<div class="page-header">
    <h1>Stores <small>list of supported stores</small></h1>
</div>
<div class="list-group">
    {% for store in stores %}
    <!-- display list of stores here -->

    <a href="{{ url_for('stores.store_page', store_id=store._id}}" class="list-group-itme">
        <h4 class="list-group-item-title">{{ store.name }}</h4>
        <p class="list-group-item-text">All URLs in this store should start with <strong>{{ store.url_prefix }}</strong></p>
    </a>

    {% endfor %}
</div>
<a class="btn btn-success" href="{{ url_for('stores.create_store') }}">
    <span class="glyphicon glyphicon-plus"></span> Create new
</a>


{% endblock %}