src/models/alerts/views.py
from flask import Blueprint, render_template, request, session, redirect, url_for
from models.alerts.alert import Alert
from models.items.item import Item
import models.users.decorators as user_decorators

# store_blueprint = Blueprint('stores', __name__)
# print('why?')
alert_blueprint = Blueprint('alerts', __name__)


@alert_blueprint.route('/')
@user_decorators.requires_login
def index():
    pass
    # return "methods not method"

# so on a hunch i commented this out and now it works? what the actual fuck
# its methods, not method


@alert_blueprint.route('/new', methods=['GET', 'POST'])
# checks that the user is logged in
@user_decorators.requires_login
def create_alert():
    if request.method == 'POST':
        name = request.form['name']
        url = request.form['url']
        price_limit = float(request.form['price_limit'])

        # def __init__(self, name, url, price=None, _id=None):
        item = Item(name, url)
        item.save_to_mongo()

        alert = Alert(session['email'], price_limit, item._id)
        alert.load_item_price()  # Already saves to mongo

    return render_template('alerts/new_alert.html')


@alert_blueprint.route('/edit/<string:alert_id>', methods=['GET', 'POST'])
@user_decorators.requires_login
def edit_alert(alert_id):
    alert = Alert.find_by_id(alert_id)

    if request.method == 'POST':
        name = request.form['name']
        url = request.form['url']
        price_limit = request.form['price_limit']

        # so some of these are actually item properties
        alert.item.name = name
        alert.item.url = url
        alert.price_limit = price_limit

        # do i need to save the item?
        alert.save_to_mongo()
        # maybe?
        alert.item.save_to_mongo()

        return redirect(url_for('users.user_alerts'))

        # experimenting
        # return get_alert_page(alert_id)

    return render_template('alerts/edit_alert.html', alert=alert)


@alert_blueprint.route('/deactivate/<string:alert_id>')
@user_decorators.requires_login
def deactivate_alert(alert_id):
    Alert.find_by_id(alert_id).deactivate()
    return redirect(url_for('users.user_alerts'))


@alert_blueprint.route('/delete/<string:alert_id>')
@user_decorators.requires_login
def delete_alert(alert_id):
    Alert.find_by_id(alert_id).delete()
    return redirect(url_for('users.user_alerts'))


@alert_blueprint.route('/activate/<string:alert_id>')
@user_decorators.requires_login
def activate_alert(alert_id):
    Alert.find_by_id(alert_id).activate()
    return redirect(url_for('users.user_alerts'))


@alert_blueprint.route('/<string:alert_id>')
@user_decorators.requires_login
def get_alert_page(alert_id):
    # print('hello from get_alert_page the alert_id is: ', alert_id)
    alert = Alert.find_by_id(alert_id)
    return render_template('/alerts/alert.html', alert=alert)


@alert_blueprint.route('/check_price/<string:alert_id>')
def check_alert_price(alert_id):
    Alert.find_by_id(alert_id).load_item_price()
    return redirect(url_for('.get_alert_page', alert_id=alert_id))

src/models/users/views.py
from flask import Blueprint, session, request, url_for, render_template
from werkzeug.utils import redirect

from models.users.user import User, UserError
import models.users.decorators as user_decorators

# print( type( user_decorators) )


user_blueprint = Blueprint('users', __name__)


@user_blueprint.route('/login', methods=['GET', 'POST'])
def login_user():
    if request.method == 'POST':
        # check login is valid
        email = request.form['email']
        password = request.form['password']

        try:
            if User.is_login_valid(email, password):
                session['email'] = email
                # gets the method user_alerts from the current location
                return redirect(url_for(".user_alerts"))
        except UserError.UserError as e:
            return e.message

    # send an error if the login was invalid
    return render_template("users/login.html")


@user_blueprint.route('/register', methods=['GET', 'POST'])
def register_user():
    if request.method == 'POST':
        # check login is valid
        email = request.form['email']
        password = request.form['password']

        try:
            if User.register_user(email, password):
                session['email'] = email
                # gets the method user_alerts from the current location
                return redirect(url_for(".user_alerts"))
        except UserError.UserError as e:
            # getting username does not exist here
            return e.message

    # changing this because i think it should be register
    # send an error if the login was invalid
    return render_template("users/register.html")


@user_blueprint.route('/alerts')
@user_decorators.requires_login
def user_alerts():
    user = User.find_by_email(session['email'])
    alerts = user.get_alerts()
    # the alert=alert passes the alert variable from above to the page so jinja can use it
    return render_template('users/alerts.html', alerts=alerts)


@user_blueprint.route('/logout')
def logout_user():
    session['email'] = None
    # home here is the base template in the app.py file which is why you don't need
    # any prefix information
    return redirect(url_for('home'))


@user_blueprint.route('/check_alerts/')
def check_user_alerts(user_id):
    pass

src/templates/users/alerts.html
{% extends "base.html" %}

{% block content %}

<div class="page-header">
    <h1>Alerts</h1>
</div>

<div class="list-group">
    {% for alert in alerts %}
    <a href="{{ url_for('alerts.get_alert_page', alert_id=alert._id) }}" class="list-group-item {{ 'list-group-item-warning' if not alert.active else '' }}">

        <h4 class="list-group-item-heading">
            <span class=" {{ 'glyphicon glyphicon-remove-circle'  if not alert.active else '' }} "></span> Alert for {{
            alert.item.name }}
        </h4>


        <p class="list-group-item-text">Last price found was <strong>{{ alert.item.price }}</strong><br />
            Last checked on <strong>{{ alert.last_checked.strftime("%d-%m-%y at %H-%M") }}</strong>
        </p>

    </a>
    {% endfor %}
    <a class="btn btn-success" href="{{ url_for('alerts.create_alert') }}"><span class="glyphicon glyphicon-plus"></span>
        Create new alert</a>
</div>

{% endblock %}

src/templates/users/login.html
{% extends "base.html" %}

{% block content %}

<div class="form-size">
    <form action="{{ url_for('users.login_user') }}" method="post">
        <div class="form-group">
            <label for="email">E-mail address</label>
            <input type="email" class="form-control" id="email" name="email" placeholder="Email">
        </div>

        <div class="form-group">
            <label for="password">Password</label>
            <input type="password" class="form-control" id="password" name="password" placeholder="password">
        </div>
        <button type="submit" class="btn btn-default">Log in</button>
    </form>
</div>

{% endblock %}

src/templates/users/register.html
{% extends "base.html" %}

{% block content %}

<div class="form-size">
    <form action="{{ url_for('users.register_user') }}" method="post">
        <div class="form-group">
            <label for="email">E-mail address</label>
            <input type="email" class="form-control" id="email" name="email" placeholder="Email">
        </div>

        <div class="form-group">
            <label for="password">Password</label>
            <input type="password" class="form-control" id="password" name="password" placeholder="password">
        </div>
        <button type="submit" class="btn btn-default">Sign up</button>
    </form>
</div>

{% endblock %}