src/models/alerts/views.py
from flask import Blueprint, render_template, request, session, redirect, url_for
from models.alerts.alert import Alert
from models.items.item import Item
import models.users.decorators as user_decorators

# store_blueprint = Blueprint('stores', __name__)
# print('why?')
alert_blueprint = Blueprint('alerts', __name__)


@alert_blueprint.route('/')
@user_decorators.requires_login
def index():
    pass
    # return "methods not method"

# so on a hunch i commented this out and now it works? what the actual fuck
# its methods, not method


@alert_blueprint.route('/new', methods=['GET', 'POST'])
# checks that the user is logged in
@user_decorators.requires_login
def create_alert():
    if request.method == 'POST':
        name = request.form['name']
        url = request.form['url']
        price_limit = float(request.form['price_limit'])

        # def __init__(self, name, url, price=None, _id=None):
        item = Item(name, url)
        item.save_to_mongo()

        alert = Alert(session['email'], price_limit, item._id)
        alert.load_item_price()  # Already saves to mongo

    return render_template('alerts/new_alert.html')


@alert_blueprint.route('/edit/<string:alert_id>', methods=['GET', 'POST'])
@user_decorators.requires_login
def edit_alert(alert_id):
    alert = Alert.find_by_id(alert_id)

    if request.method == 'POST':
        name = request.form['name']
        url = request.form['url']
        price_limit = request.form['price_limit']

        # so some of these are actually item properties
        alert.item.name = name
        alert.item.url = url
        alert.price_limit = price_limit

        # do i need to save the item?
        alert.save_to_mongo()
        # maybe?
        alert.item.save_to_mongo()

        return redirect(url_for('users.user_alerts'))

        # experimenting
        # return get_alert_page(alert_id)

    return render_template('alerts/edit_alert.html', alert=alert)


@alert_blueprint.route('/deactivate/<string:alert_id>')
@user_decorators.requires_login
def deactivate_alert(alert_id):
    Alert.find_by_id(alert_id).deactivate()
    return redirect(url_for('users.user_alerts'))


@alert_blueprint.route('/delete/<string:alert_id>')
@user_decorators.requires_login
def delete_alert(alert_id):
    Alert.find_by_id(alert_id).delete()
    return redirect(url_for('users.user_alerts'))


@alert_blueprint.route('/activate/<string:alert_id>')
@user_decorators.requires_login
def activate_alert(alert_id):
    Alert.find_by_id(alert_id).activate()
    return redirect(url_for('users.user_alerts'))


@alert_blueprint.route('/<string:alert_id>')
@user_decorators.requires_login
def get_alert_page(alert_id):
    # print('hello from get_alert_page the alert_id is: ', alert_id)
    alert = Alert.find_by_id(alert_id)
    return render_template('/alerts/alert.html', alert=alert)


@alert_blueprint.route('/check_price/<string:alert_id>')
def check_alert_price(alert_id):
    Alert.find_by_id(alert_id).load_item_price()
    return redirect(url_for('.get_alert_page', alert_id=alert_id))

src/templates/alerts/alert.html
{% extends "base.html" %}

{% block content %}
<div class="page-header">
    <h1>Alert <small>for '{{ alert.item.name }}' </small></h1>
</div>

<p>Last price found was <strong>{{ alert.item.price }}</strong></p>
<p>last checked on <strong>{{ alert.last_checked.strftime("%d-%m-%y at %H-%M") }}</strong></p>

<div class="panel panel-defualt">
    <div class="panel-body">

        <a class="btn btn-default" href="{{ alert.item.url }}" role="button">Visit site</a>


        <a class="btn btn-warning" href="{{ url_for('alerts.edit_alert', alert_id=alert._id) }}" role="button">Edit
            alert</a>


        {% if alert.active %}
        <a class="btn btn-danger" href="{{ url_for('alerts.deactivate_alert', alert_id=alert._id) }}" role="button">Deactivate
            alert</a>
        {% else %}
        <a class="btn btn-success" href="{{ url_for('alerts.activate_alert', alert_id=alert._id) }}" role="button">Activate
            alert</a>
        {% endif %}
        <!--alerts.get_alert_page-->
        <a class="btn btn-warning" href="{{ url_for('alerts.check_alert_price', alert_id=alert._id) }}" role="button">Check
            price</a>
        <a class="btn btn-danger" href="{{ url_for('alerts.delete_alert', alert_id=alert._id) }}" role="button">Delete
            alert</a>
    </div>


</div>
{% endblock %}

src/templates/alerts/create_alert.html
{% extends "base.html" %}

{% block content %}


<p>
    Create alerts page.
</p>


{% endblock %}

src/templates/alerts/edit_alert.html
{% extends "base.html" %}

{% block content %}
<div class="page-header">
    <h1>Edit alert</h1>

</div>

<div class="form-size">
    <!--sends data to the same page-->
    <form method="post">

        <div class="form-group">
            <label for="name">Alert name</label>
            <input type="text" class="form-control" id="name" name="name" placeholder="Alert name" value="{{ alert.item.name }}">
        </div>

        <div class="form-group">
            <label for="url">URL</label>
            <input type="text" class="form-control" id="url" name="url" placeholder="http://.." value="{{ alert.item.url }}"
                aria-describedby="urlHelpBlock">
            <span id="urlHelpBlock" class="help-block">
                Update the URL?</span>
        </div>

        <div class="form-group">
            <label for="price_limit">Price alert limit</label>
            <!--json does not accept single quotation marks-->
            <input type="text" class="form-control" id="price_limit" name="price_limit" placeholder="45.00" value="{{ alert.price_limit }}"
                aria-describedby="queryHelpBlock">

            <span id="searchQuery" class="help-block">
                What should the new price limit be?</span>
        </div>


        <button type="submit" class="btn btn-warning">Update</button>

    </form>

</div>

{% endblock %}

src/templates/alerts/new_alert.html
{% extends "base.html" %}

{% block content %}
<div class="page-header">
    <h1>Create alert</h1>
</div>
<div class="form-size">
    <form method="POST">
        <div class="form-group">
            <label for="name">Alert/Item.name</label>
            <input type="text" class="form-control" id="name" name="name" placeholder="Item name">
        </div>

        <div class="form-group">
            <label for="url">URL</label>
            <input type="text" class="form-control" id="url" name="url" placeholder="http://..">
        </div>


        <div class="form-group">
            <label for="price_limit">Price alert limit</label>
            <input type="" class="form-control" id="price_limit" name="price_limit" placeholder="Price limit e.g. 45.00"
                aria-describedby="priceLimitBlock">
            <p id="priceLimitBlock" class="help-block">We'll send you an email when the price reaches or goes under
                this amount.</p>
        </div>
        <button type="submit" class="btn btn-default">Create</button>
</div>
{% endblock %}