src/models/stores/views.py
from flask import Blueprint, render_template, request, redirect, url_for
from models.stores.store import Store
import json

import models.users.decorators as user_decorators

store_blueprint = Blueprint('stores', __name__)


@store_blueprint.route('/')
def index():
    # print('should be getting here?')
    stores = Store.all()
    # return 'hello'
    return render_template('stores/store_index.html', stores=stores)


@store_blueprint.route('/store/<string:store_id>')
def store_page(store_id):
    return render_template('stores/store.html', store=Store.get_by_id(store_id))


@store_blueprint.route('/edit/<string:store_id>', methods=['GET', 'POST'])
@user_decorators.requires_admin_permission
def edit_store(store_id):
    store = Store.get_by_id(store_id)

    if request.method == 'POST':
        name = request.form['name']
        url_prefix = request.form['url_prefix']
        tag_name = request.form['tag_name']
        # beautiful soup expects a python dict, so you get the {"id": "price-now"}
        # as a json object, this converts is to a dict, it's actually already in that format anyway right? i think so
        query = json.loads(request.form['query'])

        # because you're working on an object that already exists
        # store = Store.get_by_id(store_id)

        store.name = name
        store.url_prefix = url_prefix
        store.tag_name = tag_name
        store.query = query

        store.save_to_mongo()

        return redirect(url_for('.index'))

    return render_template('stores/edit_store.html', store=store)


@store_blueprint.route('/delete/<string:store_id>', methods=['GET'])
@user_decorators.requires_admin_permission
def delete_store(store_id):
    Store.get_by_id(store_id).delete()
    return redirect(url_for('.index'))


@store_blueprint.route('/new', methods=['GET', 'POST'])
@user_decorators.requires_admin_permission
def create_store():
    if request.method == 'POST':
        # print('create_store here, am post data now?')
        name = request.form['name']
        url_prefix = request.form['url_prefix']
        tag_name = request.form['tag_name']
        # beautiful soup expects a python dict, so you get the {"id": "price-now"}
        # as a json object, this converts is to a dict, it's actually already in that format anyway right? i think so
        query = json.loads(request.form['query'])

        # signature of the store class
        # def __init__(self, name, url_prefix, tag_name, query, _id=None):
        Store(name, url_prefix, tag_name, query).save_to_mongo()

    return render_template('stores/new_store.html')

src/templates/stores/create_store.html
{% extends "base.html" %}

{% block content %}


<p>
    Create store page.
</p>


{% endblock %}

src/templates/stores/edit_store.html
{% extends "base.html" %}

{% block content %}
<div class="page-header">
    <h1>Create store</h1>

</div>

<div class="form-size">
    <!--sends data to the same page-->
    <form method="post">

        <div class="form-group">
            <label for="name">Store name</label>
            <input type="text" class="form-control" id="name" name="name" placeholder="Store name" value="{{ store.item_id }}">
        </div>

        <div class="form-group">
            <label for="url_prefix">URL prefix</label>
            <input type="text" class="form-control" id="url_prefix" name="url_prefix" placeholder="http://..." value='{{ store.url_prefix }}'
                aria-describedby="storeURLPrefixHelp">
            <span id="storeURLPrefixHelp" class="help-block">What characters do URLs in this online store start with?</span>
        </div>

        <div class="form-group">
            <label for="tag_name">Tag name</label>
            <input type="text" class="form-control" id="tag_name" name="tag_name" placeholder="span" value='{{ store.tag_name }}'
                aria-describedby="storeTagName">
            <span id="storeTagName" class="help-block">What is the HTML tag of the item that contains the item price,
                usually <code>span</code>?</span>
        </div>

        <div class="form-group">
            <label for="query">Search query</label>
            <!--json does not accept single quotation marks-->
            <input type="text" class="form-control" id="query" name="query" placeholder='{"id": "price-now"}' value='{{ store.query | tojson }}'
                aria-describedby="queryHelpBlock">
            <span id="searchQuery" class="help-block">
                What JSON query would we have to do to find the specific tag with the price. Remember to use double
                quotation marks?</span>
        </div>

        <button type="submit" class="btn btn-warning">Update</button>

    </form>

</div>

{% endblock %}

src/templates/stores/new_store.html
{% extends "base.html" %}

{% block content %}
<div class="page-header">
    <h1>Create store</h1>

</div>

<div class="form-size">
    <!--sends data to the same page-->
    <form method="post">

        <div class="form-group">
            <label for="name">Store name</label>
            <input type="text" class="form-control" id="name" name="name" placeholder="Store name">
        </div>

        <div class="form-group">
            <label for="url_prefix">URL prefix</label>
            <input type="text" class="form-control" id="url_prefix" name="url_prefix" placeholder="http://..."
                aria-describedby="storeURLPrefixHelp">
            <span id="storeURLPrefixHelp" class="help-block">What characters do URLs in this online store start with?</span>
        </div>

        <div class="form-group">
            <label for="tag_name">Tag name</label>
            <input type="text" class="form-control" id="tag_name" name="tag_name" placeholder="span" value="span"
                aria-describedby="storeTagName">
            <span id="storeTagName" class="help-block">What is the HTML tag of the item that contains the item price,
                usually <code>span</code>?</span>
        </div>

        <div class="form-group">
            <label for="query">Search query</label>
            <!--json does not accept single quotation marks-->
            <input type="text" class="form-control" id="query" name="query" placeholder='{"id": "price-now"}'
                aria-describedby="queryHelpBlock">
            <span id="searchQuery" class="help-block">
                What JSON query would we have to do to find the specific tag with the price. Remember to use double
                quotation marks?</span>
        </div>

        <button type="submit" class="btn btn-default">Create</button>

    </form>

</div>

{% endblock %}

src/templates/stores/store.html
{% extends "base.html" %}

{% block content %}
<div class="page-header">
    <h1>Stores <small>{{ store.name }}</small></h1>
</div>
<p class="list-group-item-text">All URLs in this store should start with <strong>{{ store.url_prefix }}</strong></p>



<!--only admins can see the buttons but you have to secure the endpoints too-->
{% if session['email'] in config.ADMINS %}
<div class="panel panel-default">
    <div class="panel-body">

        <a class="btn btn-warning" href="{{ url_for('stores.edit_store', store_id=store._id) }}" role="button">
            Edit store
        </a>

        <a class="btn btn-danger" href="{{ url_for('stores.delete_store', store_id=store._id) }}" role="button">
            Delete store
        </a>

    </div>
</div>
{% endif %}






<!--<a class="btn btn-success" href="{{ url_for('stores.create_store') }}">-->
<!--<span class="glyphicon glyphicon-plus"></span> Create new-->
<!--</a>-->


{% endblock %}

src/templates/stores/store_index.html
{% extends "base.html" %}

{% block content %}
<div class="page-header">
    <h1>Stores <small>list of supported stores</small></h1>
</div>
<div class="list-group">
    {% for store in stores %}
    <!-- display list of stores here -->

    <a href="{{ url_for( 'stores.store_page', store_id=store._id ) }}" class="list-group-itme">
        <h4 class="list-group-item-title">{{ store.name }}</h4>
        <p class="list-group-item-text">All URLs in this store should start with <strong>{{ store.url_prefix }}</strong></p>
    </a>

    {% endfor %}
</div>

{% if session['email'] in config.ADMINS %}
<a class="btn btn-success" href="{{ url_for('stores.create_store') }}">
    <span class="glyphicon glyphicon-plus"></span> Create new
</a>
{% endif %}

{% endblock %}

src/templates/stores/store_list.html
{% extends "base.html" %}

{% block content %}


<p>
    Store list page.
</p>


{% endblock %}